### ISSUE TITLE
doctest netbsd base64 error

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#500] opened 2024-02-19 23:45 UTC
NetBSD test output contains:

```
Extracting doctests from doc/perf.md...
Extracting doctests from doc/syntax-spec.md...
Extracting doctests from doc/tutorial.md...
Extracting doctests from doc/ub.md...
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:147: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:171: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:193: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:279: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:304: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:323: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:340: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:407: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:423: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:438: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:466: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:506: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:518: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:538: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:56: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:622: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:68: ok
base64: Decoding failed: Inappropriate file type or format
doc/tutorial.md:96: ok
base64: Decoding failed: Inappropriate file type or format
doc/ub.md:131: ok
19 succeeded, 0 failed
```

Even though the test "succeeds", it would be nice to know what the errors are about and whether they are a bad thing.

**Comment by taahol** [comment] 2024-02-20 08:08
Cannot reproduce on NetBSD 10.

**Comment by taahol** [comment] 2024-02-20 08:32
Fixed in https://github.com/NetBSD/src/commit/ce06935bd845d78c4f88544a8993fa8f89b5b120.

**Closed** 2024-02-20 14:23 UTC
